### ISSUE TITLE
Testing actions issue

### ISSUE THREAD

**Issue by heron2014** [brainsandbrawns/ff#35]
I am trying to test actions for example : selectPage : 

```js
  it('should generate selectPage action', () => {
   
   let page = {
     title: 'Title'
    }
 
   const expected = {
      type: 'SELECT_PAGE', 
      payload: page.title
    };
    const actual = selectPage(expected.payload);

    expect(actual).to.deep.equal(expected);
  });

// I have tried to wrap res with deepFreeze but it doesn't work

```

Error:

![testing-actions](https://cloud.githubusercontent.com/assets/8476884/19020544/b0a217d6-88a3-11e6-97c8-59857698614e.png)

Why payload is ```undefined```?

Reference: 
- actions - https://github.com/brainsandbrawns/ff/blob/master/src/actions/pages.js

@minaorangina Do you maybe see what I am missing in here? 
I am not sure how to resolve it.

**Comment by minaorangina** [comment]
@heron2014 Your problem is here:
```js
 const actual = selectPage(expected.payload);
```

You're not passing the whole action down to the reducer - only the payload.  So when the reducer executes, nothing his happening.

**Comment by heron2014** [comment]
Thanks @minaorangina , 

I resolved it by passing the whole page object:

```js
 const actual = selectPage(page);
```
